name: capstone
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - cuda-cccl=12.6.77
  - cuda-cccl_win-64=12.6.77
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.6.77
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - expat=2.6.3
  - filelock=3.13.1
  - freetype=2.12.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.7.77
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpmath=1.3.0
  - networkx=3.2.1
  - numpy=2.1.1
  - numpy-base=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pillow=10.4.0
  - pip=24.2
  - pysocks=1.7.1
  - python=3.12.7
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - requests=2.32.3
  - setuptools=72.1.0
  - sqlite=3.45.3
  - sympy=1.13.2
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - vc=14.40
  - vs2015_runtime=14.40.33807
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - aiofiles==24.1.0
    - annotated-types==0.7.0
    - anyio==4.6.0
    - click==8.1.7
    - colorama==0.4.6
    - contourpy==1.3.0
    - cycler==0.12.1
    - fastapi==0.115.0
    - fonttools==4.54.1
    - fsspec==2024.9.0
    - h11==0.14.0
    - huggingface-hub==0.25.1
    - kiwisolver==1.4.7
    - matplotlib==3.9.2
    - opencv-python==4.10.0.84
    - packaging==24.1
    - pandas==2.2.3
    - psutil==6.0.0
    - py-cpuinfo==9.0.0
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - regex==2024.9.11
    - safetensors==0.4.5
    - scipy==1.14.1
    - seaborn==0.13.2
    - six==1.16.0
    - sniffio==1.3.1
    - starlette==0.38.6
    - tokenizers==0.20.0
    - torchaudio==2.4.1
    - torchvision==0.19.1
    - tqdm==4.66.5
    - transformers==4.45.1
    - tzdata==2024.2
    - ultralytics==8.3.5
    - ultralytics-thop==2.0.9
    - uvicorn==0.31.0
